name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

    - name: update submodules and build
      shell: bash
      run: |
        sudo apt-get install docker
        docker build -t logger .

# language: cpp
# services:
#   - docker
# script:
#   - docker build -t logger .